// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ip_bypass_queries.sql

package repository

import (
	"context"
)

const createIPBypass = `-- name: CreateIPBypass :one
INSERT INTO "ip_bypasses" (
    "cidr",
    "domain",
    "expires_at",
    "note",
    "created_by",
    "created_at"
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, cidr, domain, expires_at, note, created_by, created_at
`

type CreateIPBypassParams struct {
	Cidr      string
	Domain    string
	ExpiresAt int64
	Note      string
	CreatedBy string
	CreatedAt int64
}

func (q *Queries) CreateIPBypass(ctx context.Context, arg CreateIPBypassParams) (IpBypass, error) {
	row := q.db.QueryRowContext(ctx, createIPBypass,
		arg.Cidr,
		arg.Domain,
		arg.ExpiresAt,
		arg.Note,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i IpBypass
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Domain,
		&i.ExpiresAt,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredIPBypasses = `-- name: DeleteExpiredIPBypasses :execrows
DELETE FROM "ip_bypasses"
WHERE "expires_at" < ?
`

func (q *Queries) DeleteExpiredIPBypasses(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredIPBypasses, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteIPBypass = `-- name: DeleteIPBypass :exec
DELETE FROM "ip_bypasses"
WHERE "id" = ?
`

func (q *Queries) DeleteIPBypass(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIPBypass, id)
	return err
}

const deleteIPBypassForCreator = `-- name: DeleteIPBypassForCreator :execrows
DELETE FROM "ip_bypasses"
WHERE "id" = ? AND "created_by" = ?
`

type DeleteIPBypassForCreatorParams struct {
	ID        int64
	CreatedBy string
}

func (q *Queries) DeleteIPBypassForCreator(ctx context.Context, arg DeleteIPBypassForCreatorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIPBypassForCreator, arg.ID, arg.CreatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActiveIPBypassesForDomain = `-- name: ListActiveIPBypassesForDomain :many
SELECT id, cidr, domain, expires_at, note, created_by, created_at FROM "ip_bypasses"
WHERE ("domain" = ? OR "domain" = '*') AND "expires_at" > ?
`

type ListActiveIPBypassesForDomainParams struct {
	Domain    string
	ExpiresAt int64
}

func (q *Queries) ListActiveIPBypassesForDomain(ctx context.Context, arg ListActiveIPBypassesForDomainParams) ([]IpBypass, error) {
	rows, err := q.db.QueryContext(ctx, listActiveIPBypassesForDomain, arg.Domain, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpBypass
	for rows.Next() {
		var i IpBypass
		if err := rows.Scan(
			&i.ID,
			&i.Cidr,
			&i.Domain,
			&i.ExpiresAt,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIPBypasses = `-- name: ListIPBypasses :many
SELECT id, cidr, domain, expires_at, note, created_by, created_at FROM "ip_bypasses"
ORDER BY "created_at" DESC
`

func (q *Queries) ListIPBypasses(ctx context.Context) ([]IpBypass, error) {
	rows, err := q.db.QueryContext(ctx, listIPBypasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpBypass
	for rows.Next() {
		var i IpBypass
		if err := rows.Scan(
			&i.ID,
			&i.Cidr,
			&i.Domain,
			&i.ExpiresAt,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIPBypassesByCreator = `-- name: ListIPBypassesByCreator :many
SELECT id, cidr, domain, expires_at, note, created_by, created_at FROM "ip_bypasses"
WHERE "created_by" = ?
ORDER BY "created_at" DESC
`

func (q *Queries) ListIPBypassesByCreator(ctx context.Context, createdBy string) ([]IpBypass, error) {
	rows, err := q.db.QueryContext(ctx, listIPBypassesByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpBypass
	for rows.Next() {
		var i IpBypass
		if err := rows.Scan(
			&i.ID,
			&i.Cidr,
			&i.Domain,
			&i.ExpiresAt,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
